export const siteConfig = {
  name: "GVRTRAVLP",
  url: "https://www.gvrtravlp.com",
  tagline: "Escape the routine. Explore hidden places.",
  description: "Curated weekend trips and hidden gems around Bangalore & Hyderabad. Travel with strangers, become friends, and create cinematic life experiences with GVRTRAVLP.",
  keywords: [
    "GVRTRAVLP",
    "GVR Travlp",
    "GVR Travel",
    "GVR Travlp Bangalore",
    "GVR Travlp Hyderabad",
    "GVR Travlp Trips",
    "GVR Travlp Reviews",
    "GVRTRAVLP Adventure",
    "GVRTRAVLP Community",
    "GVRTRAVLP Trekking",
    "GVRTRAVLP Weekend Escapes",
    "GVRTRAVLP Hidden Gems",
    "GVRTRAVLP Travel Influencer",
    "GVRTRAVLP Contact",
    "GVRTRAVLP Official Website",
    "GVRTRAVLP Solo Travel India",
    "GVRTRAVLP Group Trips",
    "GVRTRAVLP Cinematic Travel",
    "GVRTRAVLP Founder",
    "GVRTRAVLP Social Initiative",
    "GVRTRAVLP Photos",
    "GVRTRAVLP Stories",
    "GVRTRAVLP Memories",
    "GVRTRAVLP Upcoming Trips",
    "GVRTRAVLP Booking",
    "GVRTRAVLP WhatsApp Group",
    "GVRTRAVLP Instagram",
    "GVRTRAVLP YouTube Channel",
    "GVRTRAVLP Travel Agency",
    "GVRTRAVLP Curated Experiences",
    "GVRTRAVLP South India Travel",
    "GVRTRAVLP Hidden Trails",
    "GVRTRAVLP Night Treks Bangalore",
    "GVRTRAVLP Sunrise Treks",
    "GVRTRAVLP Community Travel India",
    "GVRTRAVLP Travel Stories",
    "GVRTRAVLP Trip Suggestions",
    "GVRTRAVLP Explore",
    "GVRTRAVLP Escape Routine",
    "GVRTRAVLP Road Trips",
    "weekend trips from Bangalore",
    "hidden places near Bangalore",
    "trekking trips Karnataka",
    "weekend trips Hyderabad",
    "adventure travel India",
    "group trips for professionals",
    "cinematic travel experiences",
  ],
  whatsappNumber: "919390184813",
  email: "gvrtravlp@gmail.com",
  instagram: "https://www.instagram.com/gvr_travlp/",
  youtube: "https://www.youtube.com/@gvrtravlp1",
  logo: "https://res.cloudinary.com/dybpntnhv/image/upload/v1778274017/71046280-96b0-45ea-a354-328f2e6946cc_sjifze.jpg",
  ogImage: "/preview.jpg",
};
